abbr -a -U -- deeplink 'xcrun simctl openurl booted'
abbr -a -U -- g 'git'
abbr -a -U -- gc 'git commit'
abbr -a -U -- gca 'git commit --amend --no-edit'
abbr -a -U -- gcaa 'git commit --amend --no-edit -a'
abbr -a -U -- gcf 'git commit --fixup'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gcp 'git cherry-pick'
abbr -a -U -- gcpc 'git cherry-pick --continue'
abbr -a -U -- gcps 'git cherry-pick --skip'
abbr -a -U -- gdm 'git delete-local-merged'
abbr -a -U -- gf 'git fetch --all'
abbr -a -U -- gfp 'git push --force-with-lease'
abbr -a -U -- gpr 'git push -u && git open-pr'
abbr -a -U -- gr 'git rebase'
abbr -a -U -- gra 'git rebase --abort'
abbr -a -U -- grc 'git rebase --continue'
abbr -a -U -- gri 'git rebase -i'
abbr -a -U -- gro 'git rebase --onto'
abbr -a -U -- grs 'git rebase --skip'
abbr -a -U -- gs 'git status'
abbr -a -U -- ll 'ls -lhA'
